#ifndef CONFIG_H_
#define CONFIG_H_

#define CONFIG_NUM_WORKER_THREADS 5

#define CONFIG_NUM_DISPATCHER_THREADS 2

#define CONFIG_CONNECTION_QUEUE_SIZE (CONFIG_NUM_WORKER_THREADS * CONFIG_NUM_DISPATCHER_THREADS * 2)

#endif